### PR TITLE
Json server

### PR DESCRIPTION
**Pull request by jodelajo**
## What this feature does:
- add json server package
- add concurrently package to run react and json server simultaniously
- json server instructions in readme file

image

### CODE REVIEW

**Comment by jodelajo** [comment]
sorry, for forgetiing "feature in the branch name..."

**Comment by Reinoptland** [comment]
Nice! Good job on adding the instructions in the README

Did you know you can even make a `npm script` for this? 

That might be _even_ easier for your colleagues than looking up the command in the readme

Here is an example: 

https://medium.com/@joelazarz/using-concurrently-with-json-server-and-your-react-app-3d07487acc50

Note: using `proxy` here is not needed, just us the `dev` script example

**Review by Reinoptland — CHANGES_REQUESTED** [review]
Add a npm script to make it easier for you colleagues

**Review by Reinoptland — APPROVED** [review]
Looks great - good job on putting it in the readme as well 👍

**Comment by Reinoptland** [comment]
@jodelajo You can merge this. Don't forget to go back to development on your own machine and pull your own changes.

**Pull request merged**
